### ISSUE TITLE
os.environ['OLLAMA_ORIGINS'] 

### ISSUE THREAD

**Issue by ffreemt** [Luxadevi/Ollama-Colab-Integration#1]
Hello thanks for making this available.

I have a question on setting `os.environ['OLLAMA_ORIGINS'] = 'http://85.145.210.99:*'` in
`https://github.com/Luxadevi/Ollama-Colab-intergration/blob/main/Ollama_public.ipynb`. Should the IP here be the IP of the nat-tunnel server, right?

**Comment by Luxadevi** [comment]
I think 0.0.0.0 works as well that way it accepts from wherever. So i updated that part.
Im working on a revised version where we first start ollama and afterwards the tunnel.
This version will run those two in the background and check your api url if its available if its not available it will restart one of the services.
Also will include input fields for the ip and secretpass

**Comment by Luxadevi** [comment]
I released a new version with advanced logging and background tasking.
I'll close this issue and hope you try the new one.

**Comment by Luxadevi** [comment]
I released a new version with advanced logging and background tasking.
I'll close this issue and hope you try the new one.
