### ISSUE TITLE
infinite loop?

### ISSUE THREAD

**Issue by junioralive** [Luxadevi/Ollama-Colab-Integration#5]
i ran the collab file for 20 min still got nothing

**Comment by Luxadevi** [comment]
The newer versions of llama.cpp take a while to compile.


Change line:
```
!/content/Ollama-Companion/install.sh 2> /dev/null 1>&2
```

To:
```
!/content/Ollama-Companion/install.sh -minimal
```

This will skip the installation of llama.cpp and will not let you quantize models, if you only want to interact with Ollama this is not needed.

**Comment by Luxadevi** [comment]
Changed a line for the starting script to make it potentially run better, this notebook was using an older startup script.

If you want to get output from the notebook about what its doing remove all 
```
2> /dev/null 1>&2
```

**Comment by junioralive** [comment]
can you please provide eta for it to run, like a average time

**Comment by Luxadevi** [comment]
With changing the line i provided in the first answer around 2-5 minutes. Without doing this up to 10 minutes.

**Comment by junioralive** [comment]
should i give any input here 

![image](https://github.com/Luxadevi/Ollama-Colab-Integration/assets/54473944/b0470a24-6612-49e7-a417-6093a2c195d3)

becase im getting a input box here

**Comment by Luxadevi** [comment]
Hey buddy, i made a mistake when i updated the installer, the success message actually got pushed to /dev/null, 

I hope in the meanwhile the tips and instructions made it work,
I updated the notebook and also removes some redundant commands, and with that im going to close this issue.


Feel free to reopen this issue if you still encounter some problems.

Gr 
Luxa
