### ISSUE TITLE
Unable to download models

### ISSUE THREAD

**Issue by junioralive** [Luxadevi/Ollama-Colab-Integration#6]
Error creating model: HTTPConnectionPool(host='127.0.0.1', port=11434): Max retries exceeded with url: /api/create (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7e323af058d0>: Failed to establish a new connection: [Errno 111] Connection refused'))

**Comment by junioralive** [comment]
![image](https://github.com/Luxadevi/Ollama-Colab-Integration/assets/54473944/0c0c380c-dfae-4122-9c68-452830ced9be)

**Comment by junioralive** [comment]
![image](https://github.com/Luxadevi/Ollama-Colab-Integration/assets/54473944/324d5677-1af4-484c-a765-948460bfbaf2)

**Comment by Luxadevi** [comment]
Oh let me look at that.
Let met get back to you.

**Comment by Luxadevi** [comment]
Hey man sorry for the issues.

Was not configured for the newer installer, i  and did not like the python virtual enviroment.
Brought Ollama.py over from Colab_installer branch and changed the installer and runners to also prevent using extra resources.
Added some more arguments to the  installer you can now use

```
-colab
```
or 
```
-colab_compile
```

Will now standard use precomiled version of llama.cpp so the installer is  quick and can be more customized see the install script for more information.  


Use the -colab_compile argument to clone the llama.cpp en compile fresh binaries.

Can i refer back to the new file:  

https://github.com/Luxadevi/Ollama-Colab-Integration/blob/main/Ollama_ColabV4_5.ipynb

Happy to hear from ya!


Gr 
Luxa

**Comment by junioralive** [comment]
Thank a lot its working completly fine <3

**Comment by junioralive** [comment]
Can you also suggest some best settings for, Model File Creator for collab environment

**Comment by Luxadevi** [comment]
You could use this post as a reference gui

https://www.reddit.com/r/LocalLLaMA/comments/17vonjo/your_settings_are_probably_hurting_your_model_why/

General tip is to keep LLAVA for images very low temperature so: 0.1 is enough(As referenced by LLAVA papaer)

I'm using mostly default and generally only increasing when needed. 
What better works for customization is crafting a system prompt : 
```
You are a helpful Ai assistant focused on writing Linux and Python.When a bash script can be used instead of Python generate both within a code-block. Also recall where more information about Modules and Libraries can be found.
```
This is one for more python focused CodingBot for example

Also when using a INSTRUCT template you can use Almost any English NLP to get a answer
that is more in line of what you need or want.

Gr
Luxa

**Comment by Luxadevi** [comment]
I will close this issue for now, if you have any questions or issues then feel free open a new isue or to re-open  this issue by commenting on it. 

Gr
Luxa
